"""
PDF Report Generator for Pakistani Legal & Tax Advisory
Uses fpdf2 to build professional, boardroom-ready Tax Assessment Memorandums.
"""

from datetime import datetime
from typing import Dict, Any, Optional
from fpdf import FPDF


def sanitize_text(text: str) -> str:
    """Replaces Unicode characters that standard core PDF fonts cannot encode."""
    if not text:
        return ""
    replacements = {
        "\u2014": "-",   # em dash
        "\u2013": "-",   # en dash
        "\u2018": "'",   # left single quote
        "\u2019": "'",   # right single quote
        "\u201c": '"',   # left double quote
        "\u201d": '"',   # right double quote
        "\u2022": "*",   # bullet
        "\u2026": "...", # ellipsis
        "₹": "PKR ",
        "•": "*",
        "⚖": "",
        "🧮": "",
        "📄": "",
        "⚠️": "",
        "📌": "",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    # Filter non-latin1 characters to avoid FPDF standard font encoding errors
    return text.encode("latin-1", "replace").decode("latin-1")


class TaxAdvisoryPDF(FPDF):
    def header(self):
        # Top banner
        self.set_fill_color(15, 23, 42)  # Dark slate navy
        self.rect(0, 0, 210, 24, "F")
        self.set_xy(10, 6)
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(255, 255, 255)
        self.cell(0, 7, "PAKISTAN STATUTORY TAX & LEGAL ADVISORY", ln=True, align="L")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 4, "INCOME TAX ORDINANCE 2001 | FINANCE ACT 2024-2026 | SECP COMPLIANCE", ln=True, align="L")
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        page_str = f"Page {self.page_no()}/{{nb}} - Generated by Legal Research Assistant"
        self.cell(0, 10, page_str, align="C")


def generate_tax_pdf_report(
    calc_data: Dict[str, Any],
    advisory_memo: str = "",
    taxpayer_name: str = "Corporate / Business Client",
    reference_id: Optional[str] = None,
) -> bytes:
    """
    Generates a formal PDF Tax Assessment Memorandum.
    Returns bytes suitable for Streamlit st.download_button.
    """
    pdf = TaxAdvisoryPDF(orientation="P", unit="mm", format="A4")
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=18)

    date_str = datetime.now().strftime("%d %B %Y")
    ref_str = reference_id or f"TAX-REF-{datetime.now().strftime('%Y%m%d-%H%M')}"

    # Document Title Block
    pdf.set_y(28)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 7, "CONFIDENTIAL TAX ASSESSMENT MEMORANDUM", ln=True, align="C")
    pdf.ln(2)

    # Metadata Bar
    pdf.set_fill_color(241, 245, 249)
    pdf.rect(10, pdf.get_y(), 190, 14, "F")
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(51, 65, 85)

    y_pos = pdf.get_y() + 2
    pdf.set_xy(14, y_pos)
    pdf.cell(40, 5, f"TAXPAYER: {sanitize_text(taxpayer_name)}")
    pdf.cell(50, 5, f"REF NO: {ref_str}")
    pdf.cell(50, 5, f"DATE: {date_str}")
    pdf.cell(45, 5, f"TAX YEAR: {calc_data.get('tax_year', '2024-2025')}", ln=True)

    y_pos2 = pdf.get_y()
    pdf.set_xy(14, y_pos2)
    pdf.cell(60, 5, f"CATEGORY: {calc_data.get('category', 'Salaried')}")
    pdf.cell(130, 5, f"STATUTORY BASIS: {sanitize_text(calc_data.get('statutory_reference', 'Income Tax Ordinance 2001'))}", ln=True)
    pdf.ln(5)

    # Section 1: Financial Computation Summary
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 6, "1. STATUTORY TAX LIABILITY SCHEDULE", ln=True)
    pdf.set_draw_color(203, 213, 225)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)

    # Table Header
    pdf.set_fill_color(30, 41, 59)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(255, 255, 255)
    col_w = [95, 45, 50]
    pdf.cell(col_w[0], 6, "Tax Assessment Component", border=1, fill=True)
    pdf.cell(col_w[1], 6, "Statutory Rate / Slab", border=1, fill=True, align="C")
    pdf.cell(col_w[2], 6, "Amount (PKR)", border=1, fill=True, align="R")
    pdf.ln()

    # Table Rows
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(30, 41, 59)

    fmt = calc_data.get("formatted", {})
    rows = [
        ("Gross Taxable Income (Annual)", "Total Gross Basis", fmt.get("annual_income", "0")),
        ("Taxable Income (Monthly Equivalent)", "Annual / 12", fmt.get("monthly_income", "0")),
        ("Base Income Tax Payable", sanitize_text(calc_data.get("slab_description", "Progressive")), fmt.get("base_tax", "0")),
    ]

    if calc_data.get("surcharge", 0) > 0:
        rows.append(("High Income Surcharge (10%)", "Finance Act 2024 (> 10M)", fmt.get("surcharge", "0")))

    if calc_data.get("super_tax_4c", 0) > 0:
        rate = calc_data.get("super_tax_rate_pct", 0)
        rows.append((f"Super Tax on High Earners (Section 4C)", f"{rate}% (Income > 150M)", fmt.get("super_tax_4c", "0")))

    advance_tax = calc_data.get("advance_tax_paid", 0)
    if advance_tax > 0:
        rows.append(("Less: Advance Tax / WHT Paid (Sec 147)", "Tax Deducted at Source", f"- PKR {advance_tax:,.0f}"))

    net_payable = calc_data.get("net_tax_payable", calc_data.get("total_annual_tax", 0))

    fill_toggle = False
    for desc, slab, amt in rows:
        fill_color = 248 if fill_toggle else 255
        pdf.set_fill_color(fill_color, fill_color, fill_color)
        pdf.cell(col_w[0], 5.5, f"  {desc}", border=1, fill=True)
        pdf.cell(col_w[1], 5.5, slab[:32], border=1, fill=True, align="C")
        pdf.cell(col_w[2], 5.5, amt + "  ", border=1, fill=True, align="R")
        pdf.ln()
        fill_toggle = not fill_toggle

    # Total Row
    pdf.set_fill_color(226, 232, 240)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(col_w[0] + col_w[1], 6, "  NET STATUTORY TAX PAYABLE / (REFUNDABLE)", border=1, fill=True)
    pdf.cell(col_w[2], 6, f"PKR {net_payable:,.0f}  ", border=1, fill=True, align="R")
    pdf.ln()

    # KPI Summary Box below table
    pdf.ln(3)
    pdf.set_fill_color(241, 245, 249)
    pdf.rect(10, pdf.get_y(), 190, 10, "F")
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(51, 65, 85)
    pdf.set_xy(14, pdf.get_y() + 2)
    eff_rate = calc_data.get("effective_tax_rate_pct", 0)
    monthly_tax = calc_data.get("total_monthly_tax", 0)
    net_monthly = calc_data.get("net_monthly_income", 0)
    pdf.cell(60, 5, f"Effective Tax Rate: {eff_rate:.2f}%")
    pdf.cell(65, 5, f"Monthly Tax Deduction: PKR {monthly_tax:,.0f}")
    pdf.cell(65, 5, f"Net Monthly Take-Home: PKR {net_monthly:,.0f}", ln=True)
    pdf.ln(5)

    # Section 2: AI Legal Advisory & Strategic Recommendations
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 6, "2. LEGAL ADVISORY & COMPLIANCE ASSESSMENT", ln=True)
    pdf.set_draw_color(203, 213, 225)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(51, 65, 85)

    clean_memo = sanitize_text(advisory_memo)
    if clean_memo:
        # Split memo lines and output nicely
        for line in clean_memo.split("\n"):
            line = line.strip()
            if not line:
                pdf.ln(1.5)
                continue
            if line.startswith("###") or line.startswith("**") and line.endswith("**"):
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(15, 23, 42)
                pdf.multi_cell(190, 5, line.replace("#", "").replace("*", "").strip())
                pdf.set_font("Helvetica", "", 8.5)
                pdf.set_text_color(51, 65, 85)
            elif line.startswith("-") or line.startswith("*"):
                pdf.multi_cell(190, 4.5, f"  * {line.lstrip('-*').strip()}")
            else:
                pdf.multi_cell(190, 4.5, line)
    else:
        pdf.multi_cell(
            190,
            4.5,
            "1. Advance Tax Payments: Ensure quarterly installment compliance under Section 147 of the Income Tax Ordinance 2001.\n"
            "2. Super Tax (Section 4C): For qualifying high earners, tax must be deposited with the annual return to avoid penalty under Section 205.\n"
            "3. Audit & Verification: Maintain audited accounts, expense receipts, and withholding certificates to rebut Section 122 notices.",
        )

    # Sign-off disclaimer
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 7.5)
    pdf.set_text_color(148, 163, 184)
    pdf.multi_cell(
        190,
        3.5,
        "Disclaimer: This memorandum is generated deterministically based on the provisions of the Pakistan Income Tax Ordinance, 2001 "
        "and the Finance Act 2024-2026. For contentious disputes or representation before Commissioner Appeals or ATIR, consult an authorized tax practitioner.",
    )

    return bytes(pdf.output())
